# Generated by Django 5.0.6 on 2024-05-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoCredit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='preapproved',
            new_name='preapproved_at',
        ),
    ]
