# Generated by Django 5.0.6 on 2024-05-10 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoCredit', '0003_alter_customers_id_alter_loans_id_alter_payments_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loans',
            old_name='outstanding_numeric',
            new_name='outstanding',
        ),
    ]
