# Generated by Django 5.0.6 on 2024-05-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoCredit', '0004_rename_outstanding_numeric_loans_outstanding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='contract_version',
            field=models.CharField(max_length=30),
        ),
    ]
