# Generated by Django 5.0.6 on 2024-05-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoCredit', '0005_alter_loans_contract_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='external_id',
            field=models.CharField(max_length=60),
        ),
    ]
