# Generated by Django 5.0.6 on 2024-05-12 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoCredit', '0007_alter_payments_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='status',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='The min allowed value is 1'), django.core.validators.MaxValueValidator(2, message='Te max allowed value is 2')]),
        ),
        migrations.AlterField(
            model_name='loans',
            name='status',
            field=models.SmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1, message='The min allowed value is 1'), django.core.validators.MaxValueValidator(4, message='Te max allowed value is 4')]),
        ),
        migrations.AlterField(
            model_name='payments',
            name='status',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='The min allowed value is 1'), django.core.validators.MaxValueValidator(2, message='Te max allowed value is 2')]),
        ),
    ]
