# Generated by Django 5.0.6 on 2024-05-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoCredit', '0008_alter_customers_status_alter_loans_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='contract_version',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
